CREATE INDEX IDX_USER_NAME ON USERS(USER_NAME);
CREATE INDEX IDX_ROLE_NAME ON ROLES(role_name);
CREATE INDEX IDX_COLLECTION_NAME ON COLLECTIONS(collection_name);
CREATE INDEX IDX_BOOK_NAME ON BOOKS(book_name);
CREATE INDEX IDX_CHAPTER_NAME ON CHAPTERS(chapter_name);
CREATE INDEX IDX_GENRE_NAME ON GENRES_TYPES(genre_name);

DROP INDEX IDX_CHAPTER_NAME