--alter session set "_ORACLE_SCRIPT"=true;
---------------------CREATE ROLES -------------------------------------------

CREATE ROLE RL_ADMIN;
CREATE ROLE RL_WRITTER;
CREATE ROLE RL_READER;

------------ADMIN-------
GRANT CONNECT TO RL_ADMIN;
GRANT CREATE SESSION TO RL_ADMIN;

GRANT SELECT ON ALL_ROLES TO RL_ADMIN;
GRANT SELECT ON ALL_USER TO RL_ADMIN;
GRANT SELECT ON ALL_COLLECTIONS TO RL_ADMIN;
GRANT SELECT ON ALL_BOOKS TO RL_ADMIN;
GRANT SELECT ON ALL_CHAPTERS TO RL_ADMIN;
GRANT SELECT ON ALL_COMMENTS TO RL_ADMIN;
GRANT SELECT ON ALL_GENRES_TYPES TO RL_ADMIN;
GRANT SELECT ON ALL_BOOKS_GENRES TO RL_ADMIN;
GRANT SELECT ON ALL_BOOKS_COLLECTIONS TO RL_ADMIN;
GRANT SELECT ON ALL_USER_ROLES TO RL_ADMIN;
GRANT SELECT ON ALL_USER_BOOKS TO RL_ADMIN;
GRANT SELECT ON ALL_USER_COLLECTIONS TO RL_ADMIN;
GRANT SELECT ON ALL_BOOKS_IN_COLLECTIONS TO RL_ADMIN;
GRANT SELECT ON ALL_CHAPTERS_IN_BOOK TO RL_ADMIN;

GRANT EXECUTE ON CREATE_USER TO RL_ADMIN;
GRANT EXECUTE ON DELETE_USER TO RL_ADMIN;
GRANT EXECUTE ON UPDATE_USER TO RL_ADMIN;
GRANT EXECUTE ON DELETE_COLLECTION TO RL_ADMIN;
GRANT EXECUTE ON CREATE_COMMENT TO RL_ADMIN;
GRANT EXECUTE ON DELETE_COMMENT TO RL_ADMIN;
GRANT EXECUTE ON UPDATE_COMMENT TO RL_ADMIN;
GRANT EXECUTE ON CREATE_GENRES_TYPE TO RL_ADMIN;
GRANT EXECUTE ON DELETE_COLLECTION TO RL_ADMIN;
GRANT EXECUTE ON DELETE_GENRES_TYPE TO RL_ADMIN;
GRANT EXECUTE ON UPDATE_GENRES_TYPE TO RL_ADMIN;
GRANT EXECUTE ON DELETE_BOOKS_COLLECTION TO RL_ADMIN;

----------Writter-------
GRANT CONNECT TO RL_WRITTER;
GRANT CREATE SESSION TO RL_WRITTER;

GRANT SELECT ON ALL_COLLECTIONS TO RL_WRITTER;
GRANT SELECT ON ALL_BOOKS TO RL_WRITTER;
GRANT SELECT ON ALL_CHAPTERS TO RL_WRITTER;
GRANT SELECT ON ALL_COMMENTS TO RL_WRITTER;
GRANT SELECT ON ALL_GENRES_TYPES TO RL_WRITTER;
GRANT SELECT ON ALL_BOOKS_GENRES TO RL_WRITTER;
GRANT SELECT ON ALL_BOOKS_COLLECTIONS TO RL_WRITTER;
GRANT SELECT ON ALL_USER_BOOKS TO RL_WRITTER;
GRANT SELECT ON ALL_USER_COLLECTIONS TO RL_WRITTER;
GRANT SELECT ON ALL_BOOKS_IN_COLLECTIONS TO RL_WRITTER;
GRANT SELECT ON ALL_CHAPTERS_IN_BOOK TO RL_WRITTER;

GRANT EXECUTE ON CREATE_BOOK TO RL_WRITTER;
GRANT EXECUTE ON DELETE_BOOK TO RL_WRITTER;
GRANT EXECUTE ON UPDATE_BOOK TO RL_WRITTER;
GRANT EXECUTE ON CREATE_CHAPTER TO RL_WRITTER;
GRANT EXECUTE ON DELETE_CHAPTER TO RL_WRITTER;
GRANT EXECUTE ON UPDATE_CHAPTER TO RL_WRITTER;
GRANT EXECUTE ON CREATE_COMMENT TO RL_WRITTER;
GRANT EXECUTE ON DELETE_COMMENT TO RL_WRITTER;
GRANT EXECUTE ON UPDATE_COMMENT TO RL_WRITTER;
GRANT EXECUTE ON CREATE_BOOKS_GENRE TO RL_WRITTER;
GRANT EXECUTE ON DELETE_BOOKS_GENRE TO RL_WRITTER;
GRANT EXECUTE ON UPDATE_BOOKS_GENRE TO RL_WRITTER;


-------------Reader-------------
GRANT CONNECT TO RL_READER;
GRANT CREATE SESSION TO RL_READER;

GRANT SELECT ON ALL_COLLECTIONS TO RL_READER;
GRANT SELECT ON ALL_BOOKS TO RL_READER;
GRANT SELECT ON ALL_CHAPTERS TO RL_READER;
GRANT SELECT ON ALL_COMMENTS TO RL_READER;
GRANT SELECT ON ALL_GENRES_TYPES TO RL_READER;
GRANT SELECT ON ALL_BOOKS_GENRES TO RL_READER;
GRANT SELECT ON ALL_BOOKS_COLLECTIONS TO RL_READER;
GRANT SELECT ON ALL_USER_BOOKS TO RL_READER;
GRANT SELECT ON ALL_USER_COLLECTIONS TO RL_READER;
GRANT SELECT ON ALL_BOOKS_IN_COLLECTIONS TO RL_READER;
GRANT SELECT ON ALL_CHAPTERS_IN_BOOK TO RL_READER;

GRANT EXECUTE ON CREATE_COMMENT TO RL_READER;
GRANT EXECUTE ON DELETE_COMMENT TO RL_READER;
GRANT EXECUTE ON UPDATE_COMMENT TO RL_READER;
GRANT EXECUTE ON CREATE_COLLECTION TO RL_READER;
GRANT EXECUTE ON DELETE_COLLECTION TO RL_READER;
GRANT EXECUTE ON UPDATE_COLLECTION TO RL_READER;
GRANT EXECUTE ON CREATE_BOOKS_COLLECTION TO RL_READER;
GRANT EXECUTE ON DELETE_BOOKS_COLLECTION TO RL_READER;
GRANT EXECUTE ON UPDATE_BOOKS_COLLECTION TO RL_READER;
