------------------------TABLESPACE--------------------------------
CREATE TABLESPACE TS_PRIME
DATAFILE 'C:\oraDB\oradata\ORCLSEC\TS_PRIME.dbf'
SIZE 100M
AUTOEXTEND ON;

DROP TABLE BOOKS_COLLECTIONS;
DROP TABLE BOOKS_GENRES;
DROP TABLE GENRES_TYPES;
DROP TABLE COMMENTS ;
DROP TABLE  CHAPTERS;
DROP TABLE BOOKS;
DROP TABLE COLLECTIONS;
DROP TABLE USERS;
DROP TABLE ROLES;

-----------------------------------CREATE TABLES----------------------------
---------------------TABLE ROLE -------------------------------------------
CREATE TABLE ROLES(
    role_id NUMBER(10) generated by default as identity PRIMARY KEY,
    role_name VARCHAR2(50)
)TABLESPACE TS_PRIME;

---------------------TABLE USERS -------------------------------------------
CREATE TABLE USERS (
   user_id NUMBER(10) generated by default as identity PRIMARY KEY,
   user_name VARCHAR2(100),
   user_email VARCHAR2(100),
   user_password VARCHAR2(100),
   user_role NUMBER(10),
   CONSTRAINT FK_USERS_ROLES FOREIGN KEY (USER_ROLE) REFERENCES ROLES (ROLE_ID)
)TABLESPACE  TS_PRIME;

---------------------TABLE COLLECTIONS -------------------------------------------
CREATE TABLE COLLECTIONS (
    collection_id NUMBER(10) generated by default as identity PRIMARY KEY,
    creator_id  NUMBER(10),
    collection_name VARCHAR2(100),
    description VARCHAR2(200),
    CONSTRAINT FK_COLLECTIONS_USERS FOREIGN KEY (CREATOR_ID) REFERENCES USERS (USER_ID)
)TABLESPACE  TS_PRIME;

---------------------TABLE BOOKS -------------------------------------------
CREATE TABLE BOOKS (
    book_id NUMBER(10) generated by default as identity PRIMARY KEY,
    creator_id  NUMBER(10),
    book_name VARCHAR2(100),
    book_publish_date DATE,
    description VARCHAR2(200),
    CONSTRAINT FK_BOOKS_USERS FOREIGN KEY (CREATOR_ID) REFERENCES USERS (USER_ID)
)TABLESPACE  TS_PRIME;

---------------------TABLE CHAPTERS -------------------------------------------
CREATE TABLE CHAPTERS (
    chapter_id NUMBER(10) generated by default as identity PRIMARY KEY,
    book_id  NUMBER(10),
    chapter_name VARCHAR2(100),
    chapter_content VARCHAR2(100),
    chapter_publish_date DATE,
    chapter_num NUMBER(10),
    CONSTRAINT FK_CHAPTERS_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
)TABLESPACE  TS_PRIME;

---------------------TABLE COMMENTS -------------------------------------------
CREATE TABLE COMMENTS (
    comment_id NUMBER(10) generated by default as identity PRIMARY KEY,
    chapter_id  NUMBER(10),
    user_id NUMBER(10),
    comment_content VARCHAR2(200),
    comment_publish_date DATE,
    CONSTRAINT FK_COMMENTS_CHAPTERS FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS (CHAPTER_ID),
    CONSTRAINT FK_COMMENTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
)TABLESPACE  TS_PRIME;

---------------------TABLE GENRES_TYPES -------------------------------------------
CREATE TABLE GENRES_TYPES (
    genre_id NUMBER(10) generated by default as identity PRIMARY KEY,
    genre_name VARCHAR2(50)
)TABLESPACE  TS_PRIME;

---------------------TABLE BOOKS_GENRES -------------------------------------------
CREATE TABLE BOOKS_GENRES (
    book_genre_id NUMBER(10) generated by default as identity PRIMARY KEY,
    genre_id NUMBER(10),
    book_id  NUMBER(10),
    CONSTRAINT FK_BOOKS_GENRES_GENRES_TYPES FOREIGN KEY (GENRE_ID) REFERENCES GENRES_TYPES (GENRE_ID),
    CONSTRAINT FK_BOOKS_GENRES_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
)TABLESPACE  TS_PRIME;

---------------------TABLE BOOKS_COLLECTIONS -------------------------------------------
CREATE TABLE BOOKS_COLLECTIONS (
    book_collection_id NUMBER(10) generated by default as identity PRIMARY KEY,
    collection_id NUMBER(10),
    book_id  NUMBER(10),
    CONSTRAINT FK_BOOKS_COLLECTIONS_GENRES_COLLECTIONS FOREIGN KEY (collection_id) REFERENCES COLLECTIONS (collection_id),
    CONSTRAINT FK_BOOKS_COLLECTIONS_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
)TABLESPACE  TS_PRIME;


