
CREATE USER ADMIN_1 IDENTIFIED BY a123;
GRANT RL_ADMIN TO ADMIN_1;
alter user ADMIN_1 default tablespace TS_PRIME; 
CREATE USER WRITTER_1 IDENTIFIED BY w123;
GRANT RL_WRITTER TO WRITTER_1;
alter user WRITTER_1 default tablespace TS_PRIME;
CREATE USER READER_1 IDENTIFIED BY r123;
GRANT RL_READER TO READER_1;
alter user READER_1 default tablespace TS_PRIME;