CREATE OR REPLACE VIEW ALL_ROLES AS
SELECT * FROM ROLES;

CREATE OR REPLACE VIEW ALL_USER AS
SELECT user_id, user_name, user_email, user_role FROM USERS;

CREATE OR REPLACE VIEW ALL_COLLECTIONS AS
SELECT * FROM COLLECTIONS;

CREATE OR REPLACE VIEW ALL_BOOKS AS
SELECT * FROM BOOKS;

CREATE OR REPLACE VIEW ALL_CHAPTERS AS
SELECT * FROM CHAPTERS;

CREATE OR REPLACE VIEW ALL_COMMENTS AS
SELECT * FROM COMMENTS;

CREATE OR REPLACE VIEW ALL_GENRES_TYPES AS
SELECT * FROM GENRES_TYPES;

CREATE OR REPLACE VIEW ALL_BOOKS_GENRES AS
SELECT * FROM BOOKS_GENRES;

CREATE OR REPLACE VIEW ALL_BOOKS_COLLECTIONS AS
SELECT * FROM BOOKS_COLLECTIONS;


CREATE OR REPLACE VIEW ALL_USER_ROLES AS
SELECT USER_ID, USER_NAME, ROLE_NAME
FROM USERS
JOIN ROLES ON USERS.USER_ROLE = ROLES.ROLE_ID
ORDER BY USER_NAME;

CREATE OR REPLACE VIEW ALL_USER_BOOKS AS
SELECT USER_ID, USER_NAME, BOOK_ID, BOOK_NAME
FROM USERS
JOIN BOOKS ON USERS.USER_ID = BOOKS.creator_id
ORDER BY USER_NAME;

CREATE OR REPLACE VIEW ALL_USER_COLLECTIONS AS
SELECT USER_ID, USER_NAME, COLLECTION_ID, COLLECTION_NAME
FROM USERS
JOIN COLLECTIONS ON USERS.USER_ID = COLLECTIONS.CREATOR_ID 
ORDER BY USER_NAME;

CREATE OR REPLACE VIEW ALL_BOOKS_IN_COLLECTIONS AS
SELECT COLLECTIONS.COLLECTION_ID, COLLECTION_NAME, BOOKS.BOOK_ID, BOOK_NAME
FROM BOOKS
JOIN BOOKS_COLLECTIONS ON BOOKS.BOOK_ID = BOOKS_COLLECTIONS.BOOK_ID
JOIN COLLECTIONS ON COLLECTIONS.COLLECTION_ID = BOOKS_COLLECTIONS.COLLECTION_ID
ORDER BY COLLECTION_NAME;

CREATE OR REPLACE VIEW ALL_CHAPTERS_IN_BOOK AS
SELECT BOOKS.book_id, book_name, book_publish_date, chapter_id, chapter_name, chapter_publish_date
FROM CHAPTERS
JOIN BOOKS ON BOOKS.book_id = CHAPTERS.book_id
order by book_name, chapter_name;

